### ISSUE TITLE
Add Jupyter notebook dependencies

### ISSUE THREAD

**Issue by DanielKotik** [atomec-project/notebooks#2]
Add dependencies of Jupyter notebook to the `Pipfile`:

```toml
[packages]
ipykernel = ...
jupyter = ...
matplotlib = ...
```

Put it in the `[packages]` section (not in the `[dev]` section as we've separated now the notebooks from the library) and be specific/explicit about the versions! This virtual environment should be reproducible in order to ensure that the notebooks will run in the distant future.
